# Generated by Django 4.2.16 on 2026-04-24 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('estimated_minutes', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='decks.deck')),
            ],
            options={
                'ordering': ['deck', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('text', 'Texto'), ('quiz', 'Quiz'), ('highlight', 'Highlight')], max_length=16)),
                ('content', models.JSONField(default=dict)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='microlearning.microlesson')),
            ],
            options={
                'ordering': ['lesson', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLessonCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='microlearning.microlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'completed_at'], name='microlearni_user_id_3a18c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userlessoncompletion',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_user_lesson_completion'),
        ),
        migrations.AddIndex(
            model_name='microlesson',
            index=models.Index(fields=['deck', 'order'], name='microlearni_deck_id_38c201_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['lesson', 'order'], name='microlearni_lesson__cb09eb_idx'),
        ),
    ]
