# Generated by Django 4.2.16 on 2026-04-24 20:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('time_spent_ms', models.IntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decks.card')),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
