# Generated by Django 4.2.16 on 2026-04-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'reviewed_at'], name='reviews_rev_user_id_2672e4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['card', 'reviewed_at'], name='reviews_rev_card_id_631852_idx'),
        ),
    ]
