# Generated by Django 4.2.16 on 2026-04-24 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', 'is_archived'], name='decks_deck_user_id_a6c7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['is_public', 'is_archived'], name='decks_deck_is_publ_c71cea_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', 'next_review'], name='decks_card_deck_id_d6778f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['next_review'], name='decks_card_next_re_c22513_idx'),
        ),
    ]
